name: PFNano production test

on:
  push:
  workflow_dispatch:
    inputs:
      recid:
        description: 'Record ID'
        required: false
        default: '24103' 
        type: string
jobs:
  test-production:
    runs-on: ubuntu-latest
    steps:
    - name: Free some disk space
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Prepare directories
      run: |
        mkdir outputs
        echo ls -l  `ls -l `
        echo 'Hello World' > outputs/hello_world.txt

    - name: Run production
      run: |
        docker run -v $(pwd):/mnt/vol -w /home/cmsusr gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_30-slc7_amd64_gcc700 /bin/bash /mnt/vol/production/pfnano/pf_production.sh github && echo "Done running pf_production.sh"
        ls
        echo ls 1
        ls mnt/vol/outputs/
        cp output.root mnt/vol/outputs/
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: Analysis Results
        path: outputs/
