name: PFNano production test

on:
  push:
  workflow_dispatch:
    inputs:
      recid:
        description: 'Record ID'
        required: false
        default: '24103' 
        type: string
jobs:
  test-production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Prepare directories
      run: |
        mkdir outputs
        echo ls -l  `ls -l `

    - name: Mount cvmfs
      uses: cvmfs-contrib/github-action-cvmfs@v2

    - name: Test cvmfs
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Test /cvmfs/cms.cern.ch ###"
        ls /cvmfs/cms.cern.ch
        echo "### /cvmfs/cms-opendata-conddb.cern.ch/ ###"
        ls /cvmfs/cms-opendata-conddb.cern.ch/

    - name: Run production
      run: |
        docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs:shared -w /home/cmsusr gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cc7-cvmfs:2023-04-04-131be08c /bin/bash /mnt/vol/production/pfnano/pf_production.sh github
        echo ls -l  `ls -l `
        cp *.root outputs
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: outputs/
